select * from route;

select * from country;
truncate table country;

insert into country(name)
values 
    ('Belarus');
insert into country(name)
values 
    ('Gvatemella');
insert into country(name)
values 
    ('Zimbabva');
insert into country(name)
values 
    ('Gvinch');
insert into country(name)
values 
    ('Lolios');
insert into country(name)
values 
    ('Dasrtu');
insert into country(name)
values 
    ('Maserty');
    
select * from country;
select * from route;


insert into route(fromcountryid, tocountryid, price)
values (13,14,100);

insert into route(fromcountryid, tocountryid, price)
values (14,15,100);

insert into route(fromcountryid, tocountryid, price)
values (15,16,100);

insert into route(fromcountryid, tocountryid, price)
values (16,17,100);


create table Report 
(
    id NUMBER GENERATED by default on null as IDENTITY,
    xm XMLTYPE
);

CREATE INDEX report_xm_idx ON Report(xm) INDEXTYPE IS CTXSYS.CONTEXT;

select * from route rt
join country cF
    on cF.id = rt.fromcountryid
join country cT
    on cT.id = rt.tocountryid;

select dbms_xmlgen.getxmltype('select * from route rt
join country cF
    on cF.id = rt.fromcountryid
join country cT
    on cT.id = rt.tocountryid')
    
    
select XMLElement("Route",
           XMLForest(
           rt.id,
           rt.fromcountryid,
           rt.tocountryid,
           rt.price,
           cF.name as "countryFromName",
           cT.name as "countryToName",
           TO_CHAR(SYSDATE,'yyyy-mm-dd hh24:mi:ss') as "date"
           )
          )
from route rt
join country cF
    on cF.id = rt.fromcountryid
join country cT
    on cT.id = rt.tocountryid;
    
    
    select TO_CHAR(SYSDATE,'yyyy-mm-dd hh24:mi:ss') from dual
    
    


CREATE OR REPLACE PROCEDURE InsertReportData AS
BEGIN
  INSERT INTO Report (xm)
  SELECT XMLElement("Route",
           XMLForest(
           rt.id,
           rt.fromcountryid,
           rt.tocountryid,
           rt.price,
           cF.name as "countryFromName",
           cT.name as "countryToName",
           TO_CHAR(SYSDATE,'yyyy-mm-dd hh24:mi:ss') as "date"
           )
          )
  FROM route rt
  JOIN country cF ON cF.id = rt.fromcountryid
  JOIN country cT ON cT.id = rt.tocountryid;
END;


EXECUTE InsertReportData;

select * from Report;

SELECT XMLQuery('/Route/ID' PASSING r.xm RETURNING CONTENT) AS ID
FROM Report r
where id = 1;

SELECT ExtractValue(r.xm, '/Route/ID') AS ID
FROM Report r
where id = 1;


SELECT ExtractValue(r.xm, '/Route/date') AS ID
FROM Report r


select * from report where id = 1
